fos_rest:
  body_listener: true
  param_fetcher_listener: true
  view:
    view_response_listener: true
    formats:
      json: true
    mime_types:
      json: ['application/json', 'application/x-json']
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json', prefer_extension: false }
  exception:
    enabled: true
